### ISSUE TITLE
papirus-config not working as expected

### ISSUE THREAD

**Issue by hystrix1** [PiSupply/PaPiRus#6]
Using `sudo papirus-config` to set the screen size has no effect:

![image](https://cloud.githubusercontent.com/assets/16988358/12703273/f5ba53b6-c836-11e5-9a0b-d26a3b9bbfb3.png)

![image](https://cloud.githubusercontent.com/assets/16988358/12703276/0e9b97dc-c837-11e5-8551-f57366e8c4d6.png)

`sudo papirus-set` has the same issue:

![image](https://cloud.githubusercontent.com/assets/16988358/12703293/708af69a-c837-11e5-8dd6-2a66bdb9e06b.png)

**Comment by hystrix1** [comment]
I just found a work-around this by editing papirus-set:
`sudo nano /usr/local/bin/papirus-set`, and editing 
`EPD_SIZE=2.7` to read `EPD_SIZE=2.0`

**Comment by eichin** [comment]
By inspection, `papirus-set` can't actually work, because set_config as-written will only *change* an existing assignment, line 22 comments out any assignment that's already in the file.  I suspect "delete line 22 of papirus-set" fixes the whole problem, but I haven't tested it.

**Comment by tvoverbeek** [comment]
The install (sudo python setup.py install) installs the wrong version of papirus-set.
THis is caused by the presence of the build directory.
Delete the build directory (under the main PaPiRus directory) and all the papirus-* files under /usr/local/bin/.
Then run the install again. This should install the right version (found in PaPiRus/bin.papirus-set).
The `EPD_SIZE=2.7` should now read `EPD_SIZE=$1` (line 25 in the right versuin).

**Comment by francesco-vannini** [comment]
Closing this as it has been fixed.

**Comment by shawaj** [comment]
A number of the functionalities of this still don't seem to work for examples these lines are obviously BS:

```
if [ "$OPTION" = "Web Interface" ]; then

	#!/bin/bash
	if (whiptail --title "Web Interface"  --yesno "Would you like to enable the web interface?" 10 60) then
	    echo "You chose Skittles Exit status was $?."
	else
	    echo "You chose M&M's. Exit status was $?."
	fi

fi

if [ "$OPTION" = "Test Mode" ]; then

	#!/bin/bash
	if (whiptail --title "Test mode"  --yesno "Do you want to enable auto test mode?" 10 60) then
	    echo "You chose Skittles Exit status was $?."
	else
	    echo "You chose M&M's. Exit status was $?."
	fi

fi
```

So will reopen this issue for now

**Comment by shawaj** [comment]
That is from here - https://github.com/PiSupply/PaPiRus/blob/master/bin/papirus-config
